### ISSUE TITLE
Can't attach PDF in "Gated Content" tab 

### ISSUE THREAD

**Issue by CJGomez415** [apsislabs/cf7-gated-content#10]
I try to attach a PDF for download in the "Gated Content" tab  section in my form. I try pressing the 'Set Gated Content" blue button but nothing happens. Not sure How I can attach a PDF to it. 
<img width="1809" alt="Screen Shot 2020-03-04 at 12 23 49 PM" src="https://user-images.githubusercontent.com/5201966/75919789-0638d980-5e13-11ea-9fcf-9e8858be97c2.png">

**Comment by CJGomez415** [comment]
SOLVED. A Themify Plugin was interfering with it. Thank you.

**Comment by wkirby** [comment]
Hi @CJGomez415 thanks for the report. I’m glad you were able to find a solution.

**Comment by CJGomez415** [comment]
thank you @wkirby  ! Awesome Plugin btw.
