### ISSUE TITLE
Logged Administrator

### ISSUE THREAD

**Issue by ghost** [apsislabs/cf7-gated-content#11]
logged in administrator should not see form 
how do I get to directly to the see content ?

thank you so much

**Comment by wkirby** [comment]
Hi @Defaultgame, I'm not 100% sure I understand the request. Are you asking how a logged-in administrator might view the form? Or are you hoping that a logged in administrator will see the form in its submitted state so that they can preview the downloadable content?

**Comment by ghost** [comment]
yep i want this but how can i do that :)  logged administrator skip filling out forms, just see gated content 👍 

**"Or are you hoping that a logged in administrator will see the form in its submitted state so that they can preview the downloadable content?"**

**Comment by wkirby** [comment]
@Defaultgame sounds reasonable enough. This will require a change to the plugin itself. I will look for some time to make this update next week.

**Comment by ghost** [comment]
> @Defaultgame sounds reasonable enough. This will require a change to the plugin itself. I will look for some time to make this update next week.

You are great Thanks

**Comment by ghost** [comment]
By the way I use this plugin for a different purpose. 
Maybe you want to look.

https://www.serkanbayrak.com/test1/vrform/

**Comment by wkirby** [comment]
Closed by #14

**Comment by wkirby** [comment]
@Defaultgame I have released version `1.4.4` of this plugin which adds a new flag for always showing the download button to admins.
