### ISSUE TITLE
Gated content download button not showing

### ISSUE THREAD

**Issue by AlanaRRae** [apsislabs/cf7-gated-content#12]
Hello, 

My gated content download button is not showing after submitting the form on this page. 

https://www.pushmindandbody.com/push-state-nation-2020-report/

Could it be something in our theme interfering?

**Comment by wkirby** [comment]
@AlanaRRae it looks like there's a JS error happening inside our gated content plugin. I will investigate further this week. Can you provide me with some information?

- What version of CF7 are you using?
- What version of CF7-gated content are you using?
- What version of Wordpress are you using?

Thanks!
Wyatt

**Comment by wkirby** [comment]
@AlanaRRae I actually was able to find the CF7 version you are using in the API response. It looks like you are on a pre-5.0 version of CF7 which is currently not supported. I've looked and it's pretty easy to add support, so I will have a new version of the plugin out today that should fix this.

**Comment by wkirby** [comment]
Closed by #13

**Comment by wkirby** [comment]
@AlanaRRae version `1.4.4` has been released with support for CF7 version 4.9.
