### ISSUE TITLE
[Feature Request] Only  the relevant file to be displayed and downloadable

### ISSUE THREAD

**Issue by hussain-attari** [apsislabs/cf7-gated-content#15]
Hi,

I took your plugin for a spin and loved it. However, I don't think the below mentioned scenario is possible. Request you to implement this feture.

I have products uploaded on woocommerce and each product has a different catalog designed for it. I want the user to enter the details before he can download the catalog.

With the current plugin I believe that we can only upload a single file or upload all the 100 catalog files irrespective of the product page the user is viewing.

I want to upload Catalog File A for Product A and Catalog File B for Product B and so on, only the file relevant to the product is shown and downloadable.

**Comment by wkirby** [comment]
Hi @h6585, I think I understand the feature request, which is to have a single form with many uploaded files, but have the downloaded file change depending on which page you're viewing the form on. Does that sound right?

I do want to flag that this might not be a great use case for your situation. We don't secure the uploaded content, so if these pages are supposed to be behind a paywall, we will do nothing to enforce that — the uploaded content will still be available in your media folder.

**Comment by wkirby** [comment]
Closing as stale
