### ISSUE TITLE
Gated content download button not showing

### ISSUE THREAD

**Issue by batmush** [apsislabs/cf7-gated-content#16]
Hi,
My download link  doesn't work. Can you please help?
See info below.
![image](https://user-images.githubusercontent.com/68167337/87233918-da69c980-c399-11ea-9d97-5a65a032470a.png)
![image](https://user-images.githubusercontent.com/68167337/87233938-0a18d180-c39a-11ea-8c60-af9799ccb931.png)

**Comment by wkirby** [comment]
@batmush I've gone to your site, but it appears you've got some problems. Notably, none of the javascript appears to be running. From your site, it looks like all the forms should be displaying in modals, but are instead rendering at the bottom of the page. Filling in the form below *Please complete the form below to download the whitepaper:*, the form submits, but not with AJAX — indicating that something is causing CF7 to fail to run its javascript.

Lastly, I'll note that the gated-content cookie is being set, so we are running all code related to the CF7 gated content plugin as expected. Unfortunately, I think you'll need to resolve some of the other issues with your page before we can really say whether there is an issue with gated content.

**Comment by batmush** [comment]
Where would you suggest to put the scripts then?

**Comment by batmush** [comment]
Where would you suggest to put the scripts then?

Kind Regards,
Bati

**Comment by wkirby** [comment]
@batmush I checked your site again, and it looks like some of the JS issues have been resolved. The forms now pop up in modals. Unfortunately, the CF7 forms are still submitting without AJAX, so the inline addition of the download button is not working. The download button should still display on reload, but you may have the option selected to always require a form submission.

If you can send me a screenshot of your gated content settings to wyatt@apsis.io I can try to help further diagnose the issue.

**Comment by batmush** [comment]
Emailed you, Wyatt

Kind Regards,
Bati

**Comment by batmush** [comment]
Hi Wyatt,

I installed the plugin you emailed me. Please test now

Kind Regards,
Bati
