### ISSUE TITLE
Dowload button color

### ISSUE THREAD

**Issue by techassistlex** [apsislabs/cf7-gated-content#21]
How do I change the download button color on a Contact Form 7 Gated Content button?

**Comment by wkirby** [comment]
@techassistlex you can style the button by targeting `.wpcf7-gated-content a.wpcf7-btn` in your CSS. In the settings panel, there are also options to disable the built-in CSS, and to change the CSS classes added to the button element. This should allow you to disable all built-in styles, and then include the CSS classes for buttons to match your theme.
