### ISSUE TITLE
Form does not appear, only download button

### ISSUE THREAD

**Issue by feetonpath** [apsislabs/cf7-gated-content#22]
I have the fields required in setup. However, when I insert the shortcode onto a new page, only the download button appears, which defeats the purpose of gated assets. Please help

**Comment by wkirby** [comment]
@feetonpath most likely you have the option "Show Download for Admin" set to true; this option checks if you are logged in to WordPress as an admin user, and if so, always shows the download button.

If this is not the case, the second most likely cause is that you have previously submitted the form, and have the form submission cookie set, which will hide the form and show the download button to repeat visitors. You can check this by visiting your page in a new browser or incognito window and seeing whether the form is displayed, or by looking in your cookies to see if a cookie that starts with `cf7_gated_content_` is set.

If you want to _always_ show the form, regardless of previous submissions, please make sure the "Always Require Form" option is set to true in the settings panel.

**Comment by feetonpath** [comment]
@wkirby Thanks for your response. I have checked and i don't have "Show Download for Admin" set to true. I also checked the cookies, and cf7_gated_content_ does not appear. I have temporarily published the page, and as you can see. The form appears, but upon clicking 'submit' there is no download button or option. You can see the page here: https://operationreengage.com/download-the-strategies-for-success-white-paper-here/
![gated_content_settings](https://user-images.githubusercontent.com/98839790/153041981-f02b5e1c-c023-4255-948f-dd0ba5c4ef7e.png)
:

**Comment by feetonpath** [comment]
@wkirby pls disregard - I got it to work! thanks again for your help.
