### ISSUE TITLE
Gated form - issues downloading PDF with IE11

### ISSUE THREAD

**Issue by sarahjaynecreative** [apsislabs/cf7-gated-content#5]
Hello, 

We are seeing some issues with the form when used in IE11. It works in chrome.

It is not consistent, so it worked for me, but not the client.

The form can be found here:

https://sttdedicated.cloud-systems.net/download-datasheet-steamairheater/

The client states...

> However, when I want to download a PDF my screen freezes and I can’t even close it with the cross at the top right. I need to go in task manager to do so. I am using Internet Explorer.

Can you take a look please?

Thanks
Sarah

**Comment by wkirby** [comment]
Looks like it may be related to this: https://stackoverflow.com/questions/23003026/jquery-ajax-hangs-ie11

Have a repro. Will fix for next release.

**Comment by sarahjaynecreative** [comment]
Ah fab - when will that be?  So that I can inform the client.
Thanks
sarah

**Comment by wkirby** [comment]
Added an option to set download button target to `_blank` or to `_self` in `1.4.0`. This should address the underlying issue here.
