### ISSUE TITLE
error fetching content

### ISSUE THREAD

**Issue by JennieDoran** [apsislabs/cf7-gated-content#8]
I am using contact form 7 gated content on my WordPress site. I have set it up on our DEV instance of the site to test out making a form that has required fields which must be submitted and then the user should see the "Download" link to our gated PDF file. It worked in one browser only (Chrome). On all other tested browsers and across all mobile tests it gives an error that says "error fetching content. please reload the page." After page refresh the download link does appear. I cannot figure out why this error is happening. While I could put a simple note with the form advising users that a reload of page my be needed, I am really not loving having an experience where a user sees an error message. Has anyone else experienced this issue? I'd be happy to share any additional info that could help find a resolution. Thanks!

**Comment by wkirby** [comment]
Hi @JennieDoran thanks for the bug report. I have not experienced this issue previously. It would be great if you could provide the following:

- The URL where you are experiencing this issue
- What WordPress theme you are running
- A complete list of plugins currently running on the site

If you are not comfortable providing this information publicly, please feel free to email me directly at wyatt@apsis.io.

**Comment by JennieDoran** [comment]
Thank you @wkirby - We are using the Enar theme. We have 32 active plug ins on the dev site where I am trying this form. I put them into the attached Word file because it is kind of a lot to paste here. I will send you the url to my form as soon as I can. Since its our DEV site I need to ask my systems admin team if it is ok to share more than this on a public forum. Also, we seem to be having a different issue now with our contact forms in general (intermittently not sending at all across the entire site, not just this form). I need to get to the bottom of that before I have you look into my issue with serving up a download link any further. Thanks for the quick response!
[PlugIns.docx](https://github.com/apsislabs/cf7-gated-content/files/3617733/PlugIns.docx)

**Comment by wkirby** [comment]
@JennieDoran any update on your end? I'm happy to help, but I can't reproduce on my end.

**Comment by JennieDoran** [comment]
Hi Wyatt. I really appreciate you following up. Sorry for the delay in my response. We have decided to not use this form. You can close the issue.

**Comment by JennieDoran** [comment]
@wkirby thanks so much for following up. After noticing some other issues that are being investigated, we've decided to hold on using a form like this for now. the issue can be closed. Sorry!
